
export const PRODUCT_TYPE = {
    REQUEST_PRODUCTS_BEGIN : "REQUEST_PRODUCTS_BEGIN",
    REQUEST_PRODUCTS_SUCCESS : "REQUEST_PRODUCTS_SUCCESS",
    REQUEST_PRODUCTS_ECHEC : "REQUEST_PRODUCTS_ECHEC",
}